# Amazon Reviews 2023 Dataset Configuration
dataset:
  name: "amazon_reviews_2023"
  source: "McAuley-Lab/Amazon-Reviews-2023"
  categories:
    - "All_Beauty"
    - "Amazon_Fashion"
    - "Appliances"
    - "Arts_Crafts_and_Sewing"
    - "Automotive"
    - "Books"
    - "CDs_and_Vinyl"
    - "Cell_Phones_and_Accessories"
    - "Clothing_Shoes_and_Jewelry"
    - "Digital_Music"
    - "Electronics"
    - "Gift_Cards"
    - "Grocery_and_Gourmet_Food"
    - "Health_and_Household"
    - "Home_and_Kitchen"
    - "Industrial_and_Scientific"
    - "Kindle_Store"
    - "Musical_Instruments"
    - "Office_Products"
    - "Patio_Lawn_and_Garden"
    - "Pet_Supplies"
    - "Software"
    - "Sports_and_Outdoors"
    - "Tools_and_Home_Improvement"
    - "Toys_and_Games"
    - "Video_Games"

preprocessing:
  text_fields:
    - "title"
    - "text"
    - "features"
    - "description"
  
  min_interactions_per_user: 5
  min_interactions_per_item: 5
  max_sequence_length: 512
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  
  filtering:
    min_rating: 1.0
    max_rating: 5.0
    remove_duplicates: true
    min_text_length: 10
    max_text_length: 2000

model:
  embedding_dim: 128
  user_tower_dims: [512, 256, 128]
  item_tower_dims: [512, 256, 128]
  dropout_rate: 0.1
  l2_regularization: 1e-6
  
  training:
    batch_size: 1024
    learning_rate: 0.001
    epochs: 50
    patience: 5
    validation_freq: 1
    
  retrieval:
    candidate_sampling: "in_batch"
    temperature: 0.1
    top_k_eval: [1, 5, 10, 20, 50, 100]